### ISSUE TITLE
Add pause command between layers

### ISSUE THREAD

**Issue by gin66** [p3d-dev/Print-To-3D#1]
Great to have finally a slicer on iPad and the sliced view is just great.

Is there a way to pause the print after a selectable layer, so that filament can be changed or e.g. a magnet embedded in the part ?

**Comment by p3d-dev** [comment]
Thanks for your proposal. Currently it is not possible to add commands as requested.

Eventually we will add this as a feature in one of the next releases.

**Comment by p3d-dev** [comment]
Version 2.15 will have a feature to insert pause commands on any layer you need. Please check it out, as soon as Apple finishes their check process.
