### ISSUE TITLE
Ender 3 s1 pro extrusion values

### ISSUE THREAD

**Issue by njohnson13** [p3d-dev/Print-To-3D#12]
Every time that I use this to slice anything it does not seem to extrude correctly. Calculations in mainsail show it using well under half as much filament compared to the identical, file, sliced identically, in cura.

**Comment by p3d-dev** [comment]
Thanks for highlighting this, so quick test was made using 3DBenchy.
Cura without support, 0.25mm slice height and 25% grid infill needs 4,56m of filament.
PrintTo3D with similar settings (no support, 0.25mm slice hight, 25% grid infill) needs 4,82m of filament.
The filament length information has been retrieved from the respective slicer.

Could you please share the generated gcode files, so we can have a check ?

**Comment by p3d-dev** [comment]
stale
