### ISSUE TITLE
Operation couldn’t be completed - error while slicing

### ISSUE THREAD

**Issue by dallombra** [p3d-dev/Print-To-3D#19]
Hello, I keep getting this error when trying to slice my model

I’m running the app on a M4 iPad Pro with the top tier of hardware.

![IMG_0067](https://github.com/p3d-dev/Print-To-3D/assets/8121975/f63d970a-dc7a-4c9b-9996-460913b933b8)

Also for some reason the scale of the model is all wrong when imported in the app, like it’s 1/10 of what it should be.

**Comment by p3d-dev** [comment]
Thank you for contacting us. The screenshot you provided is very helpful. The error code indicates that the slicer did not generate any G-code commands. One possible reason could be that the STL file has issues, such as duplicated or mirrored faces. Could you share the design file with us for further investigation?

STL files contain numerical data without specific units. They are typically in millimeters, but sometimes they can be in centimeters, mils, or inches. PrintTo3D attempts to guess the unit based on the size of the object compared to the print bed. If the unit is incorrect, you can manually change it. Here’s how:

Select the object to highlight it in green and display the toolbox.
In the toolbox, press the button with the number "1" inside a square.
Change the units within reasonable limits.

We hope this helps. Thank you for using PrintTo3D!

**Comment by dallombra** [comment]
Hello, thanks for the reply, what is the best option for me to send you the stl file?

Also, I think I figured out the issue with scale: if the model is initially bigger than the print plate size, the app will automatically scale it down. I checked a couple of files and this seems the consistent behaviour. The issue is that the object may be bigger on the x & y, but a simple rotation would make it fit, but the scale will be off already and it seems once you start messing about with scale inside the app, you get those errors while slicing.

Finally, I got the same error even for a model that would fit right away.

Let me know how to share the files and I’ll send a few examples over.

**Comment by p3d-dev** [comment]
You can send the STL file to stl2024@vicinity-international.de, or alternatively, you might be able to attach the STL file directly to this comment on GitHub.

Thank you for your feedback regarding the limitations of the current implementation. We've added your insights to our list of customer proposals and will address them in the future.

Changing the scale should not affect the slicing results. All scale adjustments, movements, and rotations are combined into a single matrix. This matrix is then applied to the STL data during display and when creating the consolidated STL for the slicing engine.

**Comment by dallombra** [comment]
I’ve just sent them over via email as GitHub wouldn’t let me upload stl files here.

**Comment by p3d-dev** [comment]
Thank you for sending over the files. We were able to open them successfully in PrintTo3D and, after rearranging and resizing the models, all three have been sliced without encountering the error from your initial post. However, the results varied.

Regarding each model:

* Porta Tablet Centrale.stl: Upon closer inspection, we found that this STL file consists of 3 subparts that may not be well-connected. The slicing engine produced unusual results with additional horizontal lines, making the output unusable. When selecting the part and clicking on the circle-i button in the top left corner, the info box indicates "Surfaces: 3". Unfortunately, PrintTo3D currently lacks support for models with multiple surfaces, so we cannot assist you further with this issue.
* Left Side.stl/Right Side.stl: The slicing results were as expected.

Based on our analysis, we recommend ensuring that the first part consists of a single surface. Additionally, please note that all walls are very thin and may be at or below the limit for extrusion, depending on the chosen scale.

As mentioned earlier, we did not encounter the error code (nozzle size set to 0.4mm) during our testing. It's possible that the process settings could be influencing the outcome. To troubleshoot further, please create a new process setting by long-pressing the double square with + in the sidebar, then selecting "Standard", and try again.

We hope this information is helpful. If you have any further questions or need additional assistance, please don't hesitate to reach out to us.

**Comment by dallombra** [comment]
Hello, thank you so much for the help. Resetting the slicer setting to default seemed to have solved the issue. I did also find the issue with the exported model of the first file I’ve sent, my bad!

Thanks again for the help, great app and great support!!
