### ISSUE TITLE
how can I add my own printer settings?

### ISSUE THREAD

**Issue by Berkusar** [p3d-dev/Print-To-3D#8]
I have Elegoo Neptune 3 Pro but I could not find the related configuration among the base printers. How can I add my printer's profile or could you help me find the configurations?

**Comment by p3d-dev** [comment]
Thanks for the inquiry. We have checked the upstream repos and seen, that the Elegoo Neptune 3 Pro is already supported. So the printer database, which is downloaded by PrintTo3D has been updated. 

Please go to the printer setting and press the "Update Profiles" button in the "BASE PRINTER" section. After download, that line after "BASE PRINTER" should state: 594 available. If all goes fine, you should find in the list of base printers the "ELEGOO NEPTUNE 3 Pro".

In case the "Update Profiles" is not available and "Downloaded" is shown. Please close PrintTo3D. After opening the app again, the "Update Profiles" button should be visible again.

**Comment by Berkusar** [comment]
Yes, it worked. Thanks a million!
