### ISSUE TITLE
How can I get settings for filament types line PLA, PETG etc.?

### ISSUE THREAD

**Issue by Berkusar** [p3d-dev/Print-To-3D#9]
I'm trying to adjust the settings manually by looking to my prusa slicer settings but I really could not understand much of the settings as they are not named same as printto3d app. Are there any presets for filament type and detail? Like if I want to print really high detail or just normal with PLA, PETG etc., are there any preset settings? or can I import settings from my prusa slicer app?

**Comment by p3d-dev** [comment]
There are currently only process settings without any presets. Mainly temperatures are filament related and all else is linked to process. Just it is not black and white. If e.g. the print speed shall be increased, then eventually the temperature needs to be increased, too. On the other side, high detail is mainly linked to layer height, line width and lower print speed as this impacts the visible surface.

For each process setting, there is a brief explanation available on tap onto the "i" button. This should help to identify similar settings like prusa. But Prusa offers hundreds of tunable parameters, so there will not always be a similar setting on PrintTo3D.

As our slicing engine is neither slic3r, nor any of slic3r forks like superslicer/prusa/cura, those process settings cannot be imported.

**Comment by Berkusar** [comment]
Thank you for the quick reply. I will try and find the correct settings manually then.
